
all: out p3

out:
	mkdir out

# p3: p3.cpp Makefile
# 	g++ p3.cpp -o out/p3 -lpthread -Wall -Werror --std=c++20

p3: p3.cpp Makefile
	g++ p3.cpp -o out/p3 -lpthread -Wall -Werror --std=c++20 -DCUSTOM_BARRIER